### ISSUE TITLE
UI: add visual confirmation when succesfull

### ISSUE THREAD

**Issue by joostvkempen** [ConductionNL/pwa-verhuizen-denbosh#12]
when the information is succesfully submitted the confirmation is only textual. It would be nice to have a visual confirmation like a big green tick or something

**Comment by ginokok1996** [comment]
@joostvkempen Do you have a little bit more context for this issue?
Where do you want to see this visual confirmation?
Maybe you can clarify with a screenshot.

**Comment by joostvkempen** [comment]
![Stap 6 - Bevestiging](https://user-images.githubusercontent.com/37901988/138107535-80af6f24-547e-4f16-aca5-6bf01520c060.png)
