### ISSUE TITLE
question: can the process be directly started from the page /moving ?

### ISSUE THREAD

**Issue by joostvkempen** [ConductionNL/pwa-verhuizen-denbosh#5]
When starting from root, the first page is some kind of intro page where you have to click 'starten' to start the process 'verhuizen'. We would like to start directly from the page /moving. Is this possible using a direct link? On our main website there will be an intro page of our own with a 'starten' button. We want this to start the process direct.

**Comment by ginokok1996** [comment]
Its possible to create a direct link to /moving.

This will redirect the user to the login page and after logging in it will start the process.
