### ISSUE TITLE
UI: change color of process bar to #e5e8ee

### ISSUE THREAD

**Issue by joostvkempen** [ConductionNL/pwa-verhuizen-denbosh#8]
change the color of the progress bar between the numbered bullets to #e5e8ee instead of light purple

**Comment by ginokok1996** [comment]
We changed it to the requested hex color code.

One thing to note that it is the same color as the inactive line.
Which may cause confusion.

**Comment by joostvkempen** [comment]
Hmm, I wasn't aware of that. I thought the inactive line was grey. What would you suggest? The purple line was too far off on our corporate identity. Maybe a blue tint inbetween #e5e8ee and #001759 ?

**Comment by ginokok1996** [comment]
We went with color:
#4282AE
